# Generated by Django 2.1.8 on 2019-07-26 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locally', '0002_auto_20190724_0731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('body', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='blog',
            name='hits',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
