# Generated by Django 2.1.8 on 2019-07-26 09:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locally', '0003_auto_20190726_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
