# Generated by Django 2.1.8 on 2019-07-29 04:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('locally', '0004_wish_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_contents', models.CharField(max_length=200)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.AlterField(
            model_name='wish',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='comment',
            name='wish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='locally.Wish'),
        ),
    ]
