# Generated by Django 2.1.8 on 2019-07-29 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locally', '0007_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
